CREATE DATABASE IF NOT EXISTS UseOfOperator;
USE UseOfOperator;

CREATE TABLE Information(
Id INT NOT NULL,
Name VARCHAR(50) NOT NULL,
Grade VARCHAR(20),
CGPA FLOAT,
PRIMARY KEY(Id, Name)
);

INSERT INTO Information
VALUES
(10,"DHAKA", "A", 3.12),
(20,"RJSHAHI", "A+", 4.00),
(15,"DHAKA", "A-", 3.50),
(30,"KHULNA", "B", 2.50),
(60,"CUMILLA", "F", 0.00);

SELECT *FROM Information;
SELECT Id, Name FROM Information;
SELECT *FROM Information WHERE Id+10 > 10;
SELECT *FROM Information WHERE Id+10 < 20 AND Name = "DHAKA";
SELECT *FROM Information WHERE Id+10 >= 15 OR Name = "RAJSHAHI";

SELECT *FROM Information WHERE CGPA BETWEEN 2.50 AND 3.50;
SELECT *FROM Information WHERE Name IN ("DHAKA", "CHITTAGANG", "CUMILLA");
SELECT *FROM Information WHERE Name NOT IN ("DHAKA", "CHITTAGANG", "CUMILLA");

SELECT *FROM Information LIMIT 2;
SELECT *FROM Information WHERE Id<30 LIMIT 3;
SELECT *FROM Information ORDER BY CGPA ASC;
SELECT *FROM Information ORDER BY CGPA DESC;
SELECT *FROM Information ORDER BY CGPA DESC LIMIT 3;
